import { AnnouncementBar } from '@/components/announcement-bar';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';

export default function TermsOfServicePage() {
  return (
    <div className="bg-background text-foreground">
      <AnnouncementBar />
      <Header />
      <main className="container mx-auto max-w-[1371px] px-4 py-16 sm:py-24">
        <div className="max-w-readable mx-auto">
            <h1 className="text-m-h1 md:text-h1 font-headline font-semibold mb-8">Terms of Service</h1>
            <div className="space-y-6 text-muted-foreground">
                <p>THIS DOCUMENT IS AN ELECTRONIC RECORD in terms of the Information Technology Act, 2000 (“IT Act”) and rules issued thereunder, as applicable, and the provisions pertaining to electronic records in various statutes as amended by the IT Act. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                <p>This document is published in accordance with applicable laws, including the Consumer Protection (E-Commerce) Rules, 2020, which require publishing the rules and regulations, privacy policy, and terms and conditions for access or usage of the website.</p>
                
                <h2 className="text-m-h2 md:text-h2 font-headline font-semibold text-foreground !mt-12">1. Acceptance of Terms</h2>
                <p>Please read these Terms and Conditions (“T&C”) carefully. By accessing, browsing, or using www.enbetechserv.com (the “Website”) or availing any products or services offered by eNBe TechServ Private Limited (hereinafter referred to as “Company”, “we”, “us”, or “our”), you agree to be bound by these T&C.</p>
                <p>Only persons who can enter into legally binding contracts under the Indian Contract Act, 1872 are eligible to use the Website. Any minor must use the Website under the supervision of a parent or legal guardian.</p>
                <p>If you represent an entity, you confirm that you are authorized to bind that entity to these T&C.</p>

                <h2 className="text-m-h2 md:text-h2 font-headline font-semibold text-foreground !mt-12">2. Nature of Business</h2>
                <p>eNBe TechServ is a provider and reseller of advanced physiotherapy and rehabilitation solutions across India. We deliver high-performance medical and therapeutic equipment sourced from reputed brands to clinics, hospitals, and sports rehabilitation centers.</p>
                <p>The Company does not manufacture the equipment unless explicitly stated. All products are supplied directly from original brands or authorized distributors.</p>

                <h2 className="text-m-h2 md:text-h2 font-headline font-semibold text-foreground !mt-12">3. Modification of Terms</h2>
                <p>The Company reserves the right to modify these T&C at any time by posting an updated version on the Website. The revised T&C shall be effective immediately upon posting. Continued use of the Website constitutes acceptance of the updated T&C.</p>

                <h2 className="text-m-h2 md:text-h2 font-headline font-semibold text-foreground !mt-12">4. Products and Services</h2>
                <p>The Website offers physiotherapy, rehabilitation, and medical equipment (“Products”) for sale or inquiry.</p>
                <p>Product images are indicative and may differ from the actual product.</p>
                <p>Prices, availability, and specifications are subject to change without notice.</p>
                <p>Product warranties are provided by the original brand/manufacturer, not by eNBe TechServ, unless explicitly stated otherwise.</p>
                <p>Products are intended for professional or clinical use only unless otherwise mentioned.</p>

                <h2 className="text-m-h2 md:text-h2 font-headline font-semibold text-foreground !mt-12">5. Orders and Payments</h2>
                <p>Orders may be placed through the Website or via direct communication with the Company.</p>
                <p>Accepted payment methods include:</p>
                <ul className="list-disc list-inside space-y-2 pl-4">
                    <li>Credit / Debit Cards</li>
                    <li>Net Banking</li>
                    <li>UPI</li>
                    <li>Bank Transfer</li>
                    <li>Other approved digital payment methods</li>
                </ul>
                <p>The Company reserves the right to cancel any order in case of product unavailability, pricing errors, or suspected misuse.</p>

                <h2 className="text-m-h2 md:text-h2 font-headline font-semibold text-foreground !mt-12">6. Delivery</h2>
                <p>Delivery timelines are indicative and typically range from 5–10 business days, depending on product availability and location.</p>
                <p>Orders may be delivered in multiple shipments.</p>
                <p>The Company shall not be liable for delays caused by logistics partners, force majeure events, or circumstances beyond its control.</p>
            </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}